//! Rust code emission: one module per schema file, with `size`/`encode`/`decode` driven by a

use crate::resolve::{Field, FieldType, Message, Struct};
use crate::versions::Versions;
use std::fmt::Write;

pub struct Emitter<'a> {
    msg: &'a Message,
    out: String,
}

/// 32 levels is far more than any schema nests; `indent` clamps rather than panicking.
const INDENT: &str = "                                                                                                                                ";

fn indent(out: &mut String, levels: usize) {
    out.push_str(&INDENT[..(levels * 4).min(INDENT.len())]);
}

macro_rules! ln {
    ($out:expr, $ind:expr, $($arg:tt)*) => {{
        indent(&mut $out, $ind);
        writeln!($out, $($arg)*).unwrap();
    }};
}

impl<'a> Emitter<'a> {
    pub fn new(msg: &'a Message) -> Self {
        Emitter {
            msg,
            out: String::with_capacity(16 * 1024),
        }
    }

    fn valid(&self) -> Versions {
        self.msg.valid
    }

    /// Runtime expression deciding flexibility for a field, honouring a field-level override.
    fn flex_expr(&self, field: &Field) -> String {
        match field.flexible {
            None => "_flexible".to_string(),
            Some(v) => match v.condition(self.valid(), "version") {
                None => "true".to_string(),
                Some(c) if c == "false" => "false".to_string(),
                Some(c) => c,
            },
        }
    }

    pub fn emit(mut self) -> String {
        let m = self.msg;
        ln!(
            self.out,
            0,
            "// @generated by kafgres-codec-gen from {}.json",
            m.name
        );
        ln!(
            self.out,
            0,
            "// Kafka {}. DO NOT EDIT — see codec/VENDORING.md.",
            crate::kafka_version()
        );
        ln!(
            self.out,
            0,
            "#![allow(unused_variables, unused_mut, clippy::all)]"
        );
        self.out.push('\n');
        ln!(self.out, 0, "use crate::prelude::*;");
        self.out.push('\n');

        for s in &m.structs {
            self.emit_struct_def(s);
            self.emit_default(s);
            self.emit_impl(s);
            self.emit_sample(s);
        }

        if let Some(key) = m.api_key {
            let top = &m.structs[0];
            ln!(self.out, 0, "impl ApiMessage for {} {{", top.name);
            ln!(self.out, 1, "const API_KEY: i16 = {};", key);
            ln!(self.out, 1, "const NAME: &'static str = \"{}\";", top.name);
            ln!(
                self.out,
                1,
                "const VALID: VersionRange = VersionRange::new({}, {});",
                m.valid.lo,
                m.valid.hi
            );
            ln!(
                self.out,
                1,
                "const FLEXIBLE: VersionRange = VersionRange::new({}, {});",
                m.flexible.lo,
                m.flexible.hi
            );
            ln!(
                self.out,
                1,
                "const LATEST_VERSION_UNSTABLE: bool = {};",
                m.latest_version_unstable
            );
            ln!(self.out, 0, "}}");
            self.out.push('\n');
        }

        self.out
    }

    // struct definition + Default

    fn emit_struct_def(&mut self, s: &Struct) {
        let valid = self.valid();
        ln!(self.out, 0, "#[derive(Debug, Clone, PartialEq)]");
        ln!(self.out, 0, "pub struct {} {{", s.name);
        for f in &s.fields {
            if let Some(about) = &f.about {
                for line in wrap(about, 84) {
                    ln!(self.out, 1, "/// {}", line);
                }
            }
            ln!(
                self.out,
                1,
                "pub {}: {},",
                f.rust_name,
                f.declared_type(valid)
            );
        }
        ln!(
            self.out,
            1,
            "/// Tagged fields this build does not know. Kept so decode is forward-compatible."
        );
        ln!(
            self.out,
            1,
            "pub unknown_tagged_fields: Vec<RawTaggedField>,"
        );
        ln!(self.out, 0, "}}");
        self.out.push('\n');
    }

    fn emit_default(&mut self, s: &Struct) {
        let valid = self.valid();
        ln!(self.out, 0, "impl Default for {} {{", s.name);
        ln!(self.out, 1, "fn default() -> Self {{");
        ln!(self.out, 2, "Self {{");
        for f in &s.fields {
            ln!(self.out, 3, "{}: {},", f.rust_name, default_expr(f, valid));
        }
        ln!(self.out, 3, "unknown_tagged_fields: Vec::new(),");
        ln!(self.out, 2, "}}");
        ln!(self.out, 1, "}}");
        ln!(self.out, 0, "}}");
        self.out.push('\n');
    }

    // Encodable impl

    fn emit_impl(&mut self, s: &Struct) {
        let m = self.msg;
        let valid = m.valid;
        let flex_cond = m
            .flexible
            .condition(valid, "version")
            .unwrap_or_else(|| "true".to_string());

        let mut tagged: Vec<&Field> = s.fields.iter().filter(|f| f.tag.is_some()).collect();
        tagged.sort_by_key(|f| f.tag.unwrap());
        let plain: Vec<&Field> = s.fields.iter().filter(|f| f.tag.is_none()).collect();

        ln!(self.out, 0, "impl Encodable for {} {{", s.name);

        // ---- size ----
        ln!(self.out, 1, "fn size(&self, version: i16) -> usize {{");
        ln!(self.out, 2, "let _flexible = {};", flex_cond);
        ln!(self.out, 2, "let mut _n = 0usize;");
        for f in &plain {
            self.field_size(f, 2);
        }
        self.tagged_size(&tagged, 2);
        ln!(self.out, 2, "_n");
        ln!(self.out, 1, "}}");
        self.out.push('\n');

        // ---- encode ----
        ln!(
            self.out,
            1,
            "fn encode(&self, buf: &mut BytesMut, version: i16) -> Result<(), CodecError> {{"
        );
        ln!(self.out, 2, "let _flexible = {};", flex_cond);
        for f in &plain {
            self.field_encode(f, 2);
        }
        self.tagged_encode(&tagged, 2);
        ln!(self.out, 2, "Ok(())");
        ln!(self.out, 1, "}}");
        self.out.push('\n');

        // ---- decode ----
        ln!(
            self.out,
            1,
            "fn decode(buf: &mut Bytes, version: i16) -> Result<Self, CodecError> {{"
        );
        ln!(self.out, 2, "let _flexible = {};", flex_cond);
        for f in &plain {
            self.field_decode(f, 2);
        }
        for f in &tagged {
            ln!(
                self.out,
                2,
                "let mut {} = {};",
                f.rust_name,
                default_expr(f, valid)
            );
        }
        ln!(self.out, 2, "let mut unknown_tagged_fields = Vec::new();");
        self.tagged_decode(&tagged, 2);
        ln!(self.out, 2, "Ok(Self {{");
        for f in &s.fields {
            ln!(self.out, 3, "{},", f.rust_name);
        }
        ln!(self.out, 3, "unknown_tagged_fields,");
        ln!(self.out, 2, "}})");
        ln!(self.out, 1, "}}");

        ln!(self.out, 0, "}}");
        self.out.push('\n');
    }

    // per-field: size

    fn field_size(&mut self, f: &Field, ind: usize) {
        let valid = self.valid();
        let cond = f.versions.condition(valid, "version");
        let (ind, closing) = self.open_cond(cond, ind);
        let expr = format!("self.{}", f.rust_name);
        self.value_size(f, &expr, ind, false);
        self.close(closing, ind);
    }

    /// Accumulate the encoded size of `expr` into `_n`.
    fn value_size(&mut self, f: &Field, expr: &str, ind: usize, tagged_ctx: bool) {
        let valid = self.valid();
        let flex = self.flex_expr(f);
        if f.is_optional(valid) {
            let ncond = f.nullable.condition(valid, "version");
            match ncond {
                None => self.value_size_nullable(f, expr, ind, &flex, tagged_ctx),
                Some(c) => {
                    ln!(self.out, ind, "if {} {{", c);
                    self.value_size_nullable(f, expr, ind + 1, &flex, tagged_ctx);
                    ln!(self.out, ind, "}} else if let Some(_v) = &{} {{", expr);
                    self.size_of(&f.ty, "_v", ind + 1, &flex);
                    ln!(self.out, ind, "}}");
                }
            }
        } else {
            self.size_of(&f.ty, expr, ind, &flex);
        }
    }

    fn value_size_nullable(
        &mut self,
        f: &Field,
        expr: &str,
        ind: usize,
        flex: &str,
        tagged_ctx: bool,
    ) {
        match &f.ty {
            FieldType::Str => ln!(
                self.out,
                ind,
                "_n += nullable_string_size({}.as_deref(), {});",
                expr,
                flex
            ),
            FieldType::Bytes | FieldType::Records => ln!(
                self.out,
                ind,
                "_n += nullable_bytes_size({}.as_ref(), {});",
                expr,
                flex
            ),
            FieldType::Array(inner) => {
                ln!(self.out, ind, "match &{} {{", expr);
                ln!(
                    self.out,
                    ind + 1,
                    "None => _n += null_array_size({}),",
                    flex
                );
                ln!(self.out, ind + 1, "Some(_items) => {{");
                ln!(
                    self.out,
                    ind + 2,
                    "_n += array_len_size(_items.len(), {});",
                    flex
                );
                ln!(self.out, ind + 2, "for _item in _items.iter() {{");
                self.size_of(inner, "_item", ind + 3, flex);
                ln!(self.out, ind + 2, "}}");
                ln!(self.out, ind + 1, "}}");
                ln!(self.out, ind, "}}");
            }
            FieldType::Struct(_) => {
                // Untagged: one int8 marker. Tagged: a uvarint(1) marker inside the payload.
                ln!(self.out, ind, "match &{} {{", expr);
                if tagged_ctx {
                    ln!(self.out, ind + 1, "None => {{}}");
                    ln!(self.out, ind + 1, "Some(_v) => {{");
                    ln!(self.out, ind + 2, "_n += 1;");
                    self.size_of(&f.ty, "_v", ind + 2, flex);
                    ln!(self.out, ind + 1, "}}");
                } else {
                    ln!(self.out, ind + 1, "None => _n += 1,");
                    ln!(self.out, ind + 1, "Some(_v) => {{");
                    ln!(self.out, ind + 2, "_n += 1;");
                    self.size_of(&f.ty, "_v", ind + 2, flex);
                    ln!(self.out, ind + 1, "}}");
                }
                ln!(self.out, ind, "}}");
            }
            other => panic!("type {other:?} cannot be nullable"),
        }
    }

    /// Size of a non-null value of `ty` held in `expr`.
    fn size_of(&mut self, ty: &FieldType, expr: &str, ind: usize, flex: &str) {
        match ty {
            FieldType::Bool | FieldType::Int8 => ln!(self.out, ind, "_n += 1;"),
            FieldType::Int16 | FieldType::Uint16 => ln!(self.out, ind, "_n += 2;"),
            FieldType::Int32 | FieldType::Uint32 => ln!(self.out, ind, "_n += 4;"),
            FieldType::Int64 | FieldType::Float64 => ln!(self.out, ind, "_n += 8;"),
            FieldType::Uuid => ln!(self.out, ind, "_n += 16;"),
            FieldType::Str => ln!(self.out, ind, "_n += string_size(&{}, {});", expr, flex),
            FieldType::Bytes | FieldType::Records => {
                ln!(self.out, ind, "_n += bytes_size(&{}, {});", expr, flex)
            }
            FieldType::Struct(_) => ln!(self.out, ind, "_n += {}.size(version);", expr),
            FieldType::Array(inner) => {
                ln!(
                    self.out,
                    ind,
                    "_n += array_len_size({}.len(), {});",
                    expr,
                    flex
                );
                ln!(self.out, ind, "for _item in {}.iter() {{", expr);
                self.size_of(inner, "_item", ind + 1, flex);
                ln!(self.out, ind, "}}");
            }
        }
    }

    // per-field: encode

    fn field_encode(&mut self, f: &Field, ind: usize) {
        let valid = self.valid();
        let cond = f.versions.condition(valid, "version");
        match cond {
            None => {
                let expr = format!("self.{}", f.rust_name);
                self.value_encode(f, &expr, ind, false);
            }
            Some(c) => {
                ln!(self.out, ind, "if {} {{", c);
                let expr = format!("self.{}", f.rust_name);
                self.value_encode(f, &expr, ind + 1, false);
                // A field the negotiated version cannot carry is silently dropped. When
                if !f.ignorable {
                    ln!(self.out, ind, "}} else {{");
                    ln!(
                        self.out,
                        ind + 1,
                        "debug_assert!(self.{} == {}, \"{}.{}: non-ignorable field set at version {{}} that cannot carry it\", version);",
                        f.rust_name,
                        default_expr(f, valid),
                        self.msg.name,
                        f.name
                    );
                }
                ln!(self.out, ind, "}}");
            }
        }
    }

    fn value_encode(&mut self, f: &Field, expr: &str, ind: usize, tagged_ctx: bool) {
        let valid = self.valid();
        let flex = self.flex_expr(f);
        if f.is_optional(valid) {
            let ncond = f.nullable.condition(valid, "version");
            match ncond {
                None => self.value_encode_nullable(f, expr, ind, &flex, tagged_ctx),
                Some(c) => {
                    ln!(self.out, ind, "if {} {{", c);
                    self.value_encode_nullable(f, expr, ind + 1, &flex, tagged_ctx);
                    ln!(self.out, ind, "}} else {{");
                    ln!(
                        self.out,
                        ind + 1,
                        "let _v = {}.as_ref().ok_or(CodecError::UnexpectedNull(\"{}\"))?;",
                        expr,
                        f.name
                    );
                    self.write_of(&f.ty, "_v", ind + 1, &flex);
                    ln!(self.out, ind, "}}");
                }
            }
        } else {
            self.write_of(&f.ty, expr, ind, &flex);
        }
    }

    fn value_encode_nullable(
        &mut self,
        f: &Field,
        expr: &str,
        ind: usize,
        flex: &str,
        tagged_ctx: bool,
    ) {
        match &f.ty {
            FieldType::Str => ln!(
                self.out,
                ind,
                "put_nullable_string(buf, {}.as_deref(), {})?;",
                expr,
                flex
            ),
            FieldType::Bytes | FieldType::Records => ln!(
                self.out,
                ind,
                "put_nullable_bytes(buf, {}.as_ref(), {})?;",
                expr,
                flex
            ),
            FieldType::Array(inner) => {
                ln!(self.out, ind, "match &{} {{", expr);
                ln!(self.out, ind + 1, "None => put_null_array(buf, {}),", flex);
                ln!(self.out, ind + 1, "Some(_items) => {{");
                ln!(
                    self.out,
                    ind + 2,
                    "put_array_len(buf, _items.len(), {})?;",
                    flex
                );
                ln!(self.out, ind + 2, "for _item in _items.iter() {{");
                self.write_of(inner, "_item", ind + 3, flex);
                ln!(self.out, ind + 2, "}}");
                ln!(self.out, ind + 1, "}}");
                ln!(self.out, ind, "}}");
            }
            FieldType::Struct(_) => {
                ln!(self.out, ind, "match &{} {{", expr);
                if tagged_ctx {
                    // Null tagged struct is simply absent; the caller does not emit it.
                    ln!(self.out, ind + 1, "None => {{}}");
                    ln!(self.out, ind + 1, "Some(_v) => {{");
                    ln!(self.out, ind + 2, "put_uvarint(buf, 1);");
                    ln!(self.out, ind + 2, "_v.encode(buf, version)?;");
                    ln!(self.out, ind + 1, "}}");
                } else {
                    ln!(self.out, ind + 1, "None => put_i8(buf, -1),");
                    ln!(self.out, ind + 1, "Some(_v) => {{");
                    ln!(self.out, ind + 2, "put_i8(buf, 1);");
                    ln!(self.out, ind + 2, "_v.encode(buf, version)?;");
                    ln!(self.out, ind + 1, "}}");
                }
                ln!(self.out, ind, "}}");
            }
            other => panic!("type {other:?} cannot be nullable"),
        }
    }

    fn write_of(&mut self, ty: &FieldType, expr: &str, ind: usize, flex: &str) {
        match ty {
            FieldType::Bool => ln!(self.out, ind, "put_bool(buf, {});", deref(expr)),
            FieldType::Int8 => ln!(self.out, ind, "put_i8(buf, {});", deref(expr)),
            FieldType::Int16 => ln!(self.out, ind, "put_i16(buf, {});", deref(expr)),
            FieldType::Int32 => ln!(self.out, ind, "put_i32(buf, {});", deref(expr)),
            FieldType::Int64 => ln!(self.out, ind, "put_i64(buf, {});", deref(expr)),
            FieldType::Uint16 => ln!(self.out, ind, "put_u16(buf, {});", deref(expr)),
            FieldType::Uint32 => ln!(self.out, ind, "put_u32(buf, {});", deref(expr)),
            FieldType::Float64 => ln!(self.out, ind, "put_f64(buf, {});", deref(expr)),
            FieldType::Uuid => ln!(self.out, ind, "put_uuid(buf, &{});", expr),
            FieldType::Str => ln!(self.out, ind, "put_string(buf, &{}, {})?;", expr, flex),
            FieldType::Bytes | FieldType::Records => {
                ln!(self.out, ind, "put_bytes(buf, &{}, {})?;", expr, flex)
            }
            FieldType::Struct(_) => ln!(self.out, ind, "{}.encode(buf, version)?;", expr),
            FieldType::Array(inner) => {
                ln!(
                    self.out,
                    ind,
                    "put_array_len(buf, {}.len(), {})?;",
                    expr,
                    flex
                );
                ln!(self.out, ind, "for _item in {}.iter() {{", expr);
                self.write_of(inner, "_item", ind + 1, flex);
                ln!(self.out, ind, "}}");
            }
        }
    }

    // per-field: decode

    fn field_decode(&mut self, f: &Field, ind: usize) {
        let valid = self.valid();
        let cond = f.versions.condition(valid, "version");
        match cond {
            None => {
                ln!(self.out, ind, "let {} = {{", f.rust_name);
                self.value_decode(f, ind + 1, false);
                ln!(self.out, ind, "}};");
            }
            Some(c) => {
                ln!(self.out, ind, "let {} = if {} {{", f.rust_name, c);
                self.value_decode(f, ind + 1, false);
                ln!(self.out, ind, "}} else {{");
                ln!(self.out, ind + 1, "{}", default_expr(f, valid));
                ln!(self.out, ind, "}};");
            }
        }
    }

    /// Emit an expression-position block yielding the decoded field value.
    fn value_decode(&mut self, f: &Field, ind: usize, tagged_ctx: bool) {
        let valid = self.valid();
        let flex = self.flex_expr(f);
        if f.is_optional(valid) {
            let ncond = f.nullable.condition(valid, "version");
            match ncond {
                None => self.read_nullable(f, ind, &flex, tagged_ctx),
                Some(c) => {
                    ln!(self.out, ind, "if {} {{", c);
                    self.read_nullable(f, ind + 1, &flex, tagged_ctx);
                    ln!(self.out, ind, "}} else {{");
                    ln!(self.out, ind + 1, "Some({{");
                    self.read_of(&f.ty, ind + 2, &flex);
                    ln!(self.out, ind + 1, "}})");
                    ln!(self.out, ind, "}}");
                }
            }
        } else {
            self.read_of(&f.ty, ind, &flex);
        }
    }

    fn read_nullable(&mut self, f: &Field, ind: usize, flex: &str, tagged_ctx: bool) {
        match &f.ty {
            FieldType::Str => ln!(self.out, ind, "get_nullable_string(buf, {})?", flex),
            FieldType::Bytes | FieldType::Records => {
                ln!(self.out, ind, "get_nullable_bytes(buf, {})?", flex)
            }
            FieldType::Array(inner) => {
                ln!(self.out, ind, "match get_array_len(buf, {})? {{", flex);
                ln!(self.out, ind + 1, "None => None,");
                ln!(self.out, ind + 1, "Some(_len) => {{");
                ln!(self.out, ind + 2, "let mut _v = alloc_vec(_len);");
                ln!(self.out, ind + 2, "for _ in 0.._len {{");
                ln!(self.out, ind + 3, "_v.push({{");
                self.read_of(inner, ind + 4, flex);
                ln!(self.out, ind + 3, "}});");
                ln!(self.out, ind + 2, "}}");
                ln!(self.out, ind + 2, "Some(_v)");
                ln!(self.out, ind + 1, "}}");
                ln!(self.out, ind, "}}");
            }
            FieldType::Struct(name) => {
                if tagged_ctx {
                    ln!(self.out, ind, "if get_uvarint(buf)? == 0 {{");
                } else {
                    ln!(self.out, ind, "if get_i8(buf)? < 0 {{");
                }
                ln!(self.out, ind + 1, "None");
                ln!(self.out, ind, "}} else {{");
                ln!(self.out, ind + 1, "Some({}::decode(buf, version)?)", name);
                ln!(self.out, ind, "}}");
            }
            other => panic!("type {other:?} cannot be nullable"),
        }
    }

    fn read_of(&mut self, ty: &FieldType, ind: usize, flex: &str) {
        match ty {
            FieldType::Bool => ln!(self.out, ind, "get_bool(buf)?"),
            FieldType::Int8 => ln!(self.out, ind, "get_i8(buf)?"),
            FieldType::Int16 => ln!(self.out, ind, "get_i16(buf)?"),
            FieldType::Int32 => ln!(self.out, ind, "get_i32(buf)?"),
            FieldType::Int64 => ln!(self.out, ind, "get_i64(buf)?"),
            FieldType::Uint16 => ln!(self.out, ind, "get_u16(buf)?"),
            FieldType::Uint32 => ln!(self.out, ind, "get_u32(buf)?"),
            FieldType::Float64 => ln!(self.out, ind, "get_f64(buf)?"),
            FieldType::Uuid => ln!(self.out, ind, "get_uuid(buf)?"),
            FieldType::Str => ln!(self.out, ind, "get_string(buf, {})?", flex),
            FieldType::Bytes | FieldType::Records => {
                ln!(self.out, ind, "get_bytes(buf, {})?", flex)
            }
            FieldType::Struct(name) => ln!(self.out, ind, "{}::decode(buf, version)?", name),
            FieldType::Array(inner) => {
                ln!(self.out, ind, "match get_array_len(buf, {})? {{", flex);
                ln!(
                    self.out,
                    ind + 1,
                    "None => return Err(CodecError::UnexpectedNull(\"array\")),"
                );
                ln!(self.out, ind + 1, "Some(_len) => {{");
                ln!(self.out, ind + 2, "let mut _v = alloc_vec(_len);");
                ln!(self.out, ind + 2, "for _ in 0.._len {{");
                ln!(self.out, ind + 3, "_v.push({{");
                self.read_of(inner, ind + 4, flex);
                ln!(self.out, ind + 3, "}});");
                ln!(self.out, ind + 2, "}}");
                ln!(self.out, ind + 2, "_v");
                ln!(self.out, ind + 1, "}}");
                ln!(self.out, ind, "}}");
            }
        }
    }

    // tagged section

    /// Condition under which a tagged field is actually written: present at this
    fn tagged_write_cond(&self, f: &Field) -> String {
        let valid = self.valid();
        let vcond = f.tagged.intersect(f.versions).condition(valid, "version");
        let ne = format!("self.{} != {}", f.rust_name, default_expr(f, valid));
        match vcond {
            None => ne,
            Some(c) => format!("{c} && {ne}"),
        }
    }

    fn tagged_size(&mut self, tagged: &[&Field], ind: usize) {
        ln!(self.out, ind, "if _flexible {{");
        let i = ind + 1;
        ln!(
            self.out,
            i,
            "let mut _num_tagged = self.unknown_tagged_fields.len() as u32;"
        );
        for f in tagged {
            ln!(
                self.out,
                i,
                "if {} {{ _num_tagged += 1; }}",
                self.tagged_write_cond(f)
            );
        }
        ln!(self.out, i, "_n += uvarint_size(_num_tagged);");
        ln!(
            self.out,
            i,
            "for _f in self.unknown_tagged_fields.iter() {{"
        );
        ln!(
            self.out,
            i + 1,
            "_n += uvarint_size(_f.tag) + uvarint_size(_f.data.len() as u32) + _f.data.len();"
        );
        ln!(self.out, i, "}}");
        for f in tagged {
            let tag = f.tag.unwrap();
            ln!(self.out, i, "if {} {{", self.tagged_write_cond(f));
            ln!(self.out, i + 1, "let _outer = _n;");
            ln!(self.out, i + 1, "_n = 0;");
            let expr = format!("self.{}", f.rust_name);
            self.value_size(f, &expr, i + 1, true);
            ln!(self.out, i + 1, "let _sz = _n;");
            ln!(
                self.out,
                i + 1,
                "_n = _outer + uvarint_size({}) + uvarint_size(_sz as u32) + _sz;",
                tag
            );
            ln!(self.out, i, "}}");
        }
        ln!(self.out, ind, "}}");
    }

    fn tagged_encode(&mut self, tagged: &[&Field], ind: usize) {
        ln!(self.out, ind, "if _flexible {{");
        let i = ind + 1;
        ln!(
            self.out,
            i,
            "let mut _num_tagged = self.unknown_tagged_fields.len() as u32;"
        );
        for f in tagged {
            ln!(
                self.out,
                i,
                "if {} {{ _num_tagged += 1; }}",
                self.tagged_write_cond(f)
            );
        }
        ln!(self.out, i, "put_uvarint(buf, _num_tagged);");
        ln!(self.out, i, "let mut _ui = 0usize;");
        for f in tagged {
            let tag = f.tag.unwrap();
            // Unknown tags interleave with known ones; the wire requires ascending order.
            if tag > 0 {
                ln!(
                    self.out,
                    i,
                    "while _ui < self.unknown_tagged_fields.len() && self.unknown_tagged_fields[_ui].tag < {} {{",
                    tag
                );
                ln!(
                    self.out,
                    i + 1,
                    "let _f = &self.unknown_tagged_fields[_ui];"
                );
                ln!(self.out, i + 1, "put_uvarint(buf, _f.tag);");
                ln!(self.out, i + 1, "put_uvarint(buf, _f.data.len() as u32);");
                ln!(self.out, i + 1, "buf.extend_from_slice(&_f.data);");
                ln!(self.out, i + 1, "_ui += 1;");
                ln!(self.out, i, "}}");
            }
            ln!(self.out, i, "if {} {{", self.tagged_write_cond(f));
            ln!(self.out, i + 1, "put_uvarint(buf, {});", tag);
            // Size the payload first — the tagged framing is length-prefixed.
            ln!(self.out, i + 1, "let _sz = {{");
            ln!(self.out, i + 2, "let mut _n = 0usize;");
            let expr = format!("self.{}", f.rust_name);
            self.value_size(f, &expr, i + 2, true);
            ln!(self.out, i + 2, "_n");
            ln!(self.out, i + 1, "}};");
            ln!(self.out, i + 1, "put_uvarint(buf, _sz as u32);");
            self.value_encode(f, &expr, i + 1, true);
            ln!(self.out, i, "}}");
        }
        ln!(
            self.out,
            i,
            "while _ui < self.unknown_tagged_fields.len() {{"
        );
        ln!(
            self.out,
            i + 1,
            "let _f = &self.unknown_tagged_fields[_ui];"
        );
        ln!(self.out, i + 1, "put_uvarint(buf, _f.tag);");
        ln!(self.out, i + 1, "put_uvarint(buf, _f.data.len() as u32);");
        ln!(self.out, i + 1, "buf.extend_from_slice(&_f.data);");
        ln!(self.out, i + 1, "_ui += 1;");
        ln!(self.out, i, "}}");
        ln!(self.out, ind, "}}");
    }

    fn tagged_decode(&mut self, tagged: &[&Field], ind: usize) {
        ln!(self.out, ind, "if _flexible {{");
        let i = ind + 1;
        ln!(self.out, i, "let _num_tagged = get_uvarint(buf)?;");
        ln!(self.out, i, "let mut _last: Option<u32> = None;");
        ln!(self.out, i, "for _ in 0.._num_tagged {{");
        ln!(self.out, i + 1, "let _tag = get_uvarint(buf)?;");
        ln!(self.out, i + 1, "if let Some(_l) = _last {{");
        ln!(
            self.out,
            i + 2,
            "if _tag <= _l {{ return Err(CodecError::TagOutOfOrder {{ previous: _l, tag: _tag }}); }}"
        );
        ln!(self.out, i + 1, "}}");
        ln!(self.out, i + 1, "_last = Some(_tag);");
        ln!(self.out, i + 1, "let _sz = get_uvarint(buf)? as usize;");
        // Decode each known tag from a sub-buffer of exactly _sz bytes so a lying
        ln!(self.out, i + 1, "let mut _sub = take(buf, _sz)?;");
        ln!(self.out, i + 1, "match _tag {{");
        for f in tagged {
            let tag = f.tag.unwrap();
            ln!(self.out, i + 2, "{} => {{", tag);
            ln!(self.out, i + 3, "let buf = &mut _sub;");
            ln!(self.out, i + 3, "{} = {{", f.rust_name);
            self.value_decode(f, i + 4, true);
            ln!(self.out, i + 3, "}};");
            ln!(self.out, i + 2, "}}");
        }
        ln!(
            self.out,
            i + 2,
            "_ => unknown_tagged_fields.push(RawTaggedField {{ tag: _tag, data: _sub }}),"
        );
        ln!(self.out, i + 1, "}}");
        ln!(self.out, i, "}}");
        ln!(self.out, ind, "}}");
    }

    // sample generation (round-trip tests)

    fn emit_sample(&mut self, s: &Struct) {
        let valid = self.valid();
        let m = self.msg;
        let flex_cond = m
            .flexible
            .condition(valid, "version")
            .unwrap_or_else(|| "true".to_string());

        ln!(self.out, 0, "#[cfg(any(test, feature = \"sample\"))]");
        ln!(self.out, 0, "impl Sample for {} {{", s.name);
        ln!(
            self.out,
            1,
            "fn sample(version: i16, g: &mut Gen) -> Self {{"
        );
        ln!(self.out, 2, "let _flexible = {};", flex_cond);
        ln!(self.out, 2, "let mut _s = Self::default();");
        for f in &s.fields {
            // Only fields the version actually carries get non-default values, so
            let present = match f.tag {
                Some(_) => f.tagged.intersect(f.versions).condition(valid, "version"),
                None => f.versions.condition(valid, "version"),
            };
            let ind = match &present {
                Some(c) => {
                    let guard = if f.tag.is_some() {
                        format!("_flexible && {c}")
                    } else {
                        c.clone()
                    };
                    ln!(self.out, 2, "if {} {{", guard);
                    3
                }
                None => {
                    if f.tag.is_some() {
                        ln!(self.out, 2, "if _flexible {{");
                        3
                    } else {
                        2
                    }
                }
            };
            self.sample_assign(f, ind);
            if ind == 3 {
                ln!(self.out, 2, "}}");
            }
        }
        ln!(self.out, 2, "_s");
        ln!(self.out, 1, "}}");
        ln!(self.out, 0, "}}");
        self.out.push('\n');
    }

    fn sample_assign(&mut self, f: &Field, ind: usize) {
        let valid = self.valid();
        let target = format!("_s.{}", f.rust_name);
        if f.is_optional(valid) {
            match f.nullable.condition(valid, "version") {
                None => {
                    ln!(
                        self.out,
                        ind,
                        "{} = if g.bool() {{ None }} else {{ Some({}) }};",
                        target,
                        self.sample_expr(&f.ty)
                    );
                }
                Some(c) => {
                    ln!(
                        self.out,
                        ind,
                        "{} = if {} && g.bool() {{ None }} else {{ Some({}) }};",
                        target,
                        c,
                        self.sample_expr(&f.ty)
                    );
                }
            }
        } else {
            ln!(self.out, ind, "{} = {};", target, self.sample_expr(&f.ty));
        }
    }

    fn sample_expr(&self, ty: &FieldType) -> String {
        match ty {
            FieldType::Bool => "g.bool()".into(),
            FieldType::Int8 => "g.i8()".into(),
            FieldType::Int16 => "g.i16()".into(),
            FieldType::Int32 => "g.i32()".into(),
            FieldType::Int64 => "g.i64()".into(),
            FieldType::Uint16 => "g.u16()".into(),
            FieldType::Uint32 => "g.u32()".into(),
            FieldType::Float64 => "g.f64()".into(),
            FieldType::Uuid => "g.uuid()".into(),
            FieldType::Str => "g.string()".into(),
            FieldType::Bytes | FieldType::Records => "g.bytes()".into(),
            FieldType::Struct(n) => format!("{n}::sample(version, g)"),
            FieldType::Array(inner) => format!(
                "{{ let _k = g.array_len(); (0.._k).map(|_| {}).collect() }}",
                self.sample_expr(inner)
            ),
        }
    }

    fn open_cond(&mut self, cond: Option<String>, ind: usize) -> (usize, bool) {
        match cond {
            Some(c) => {
                ln!(self.out, ind, "if {} {{", c);
                (ind + 1, true)
            }
            None => (ind, false),
        }
    }

    fn close(&mut self, closing: bool, ind: usize) {
        if closing {
            ln!(self.out, ind - 1, "}}");
        }
    }
}

fn deref(expr: &str) -> String {
    if expr.starts_with("_item") || expr.starts_with("_v") {
        format!("*{expr}")
    } else {
        expr.to_string()
    }
}

/// The default value for a field, per `UPSTREAM-README.md` §"Deserializing Messages".
pub fn default_expr(f: &Field, valid: Versions) -> String {
    let optional = f.is_optional(valid);
    let raw = f.default.as_ref();

    // An explicit "null" default is only legal on nullable fields, except for uuid
    let is_null_default = matches!(raw, Some(serde_json::Value::String(s)) if s == "null");
    if is_null_default && !matches!(f.ty, FieldType::Uuid) {
        return "None".to_string();
    }

    let inner = match &f.ty {
        FieldType::Bool => match raw {
            Some(serde_json::Value::Bool(b)) => b.to_string(),
            Some(serde_json::Value::String(s)) => s.clone(),
            None => "false".to_string(),
            other => panic!("bad bool default {other:?}"),
        },
        FieldType::Int8
        | FieldType::Int16
        | FieldType::Int32
        | FieldType::Int64
        | FieldType::Uint16
        | FieldType::Uint32 => {
            let n = match raw {
                None => 0i64,
                Some(v) => parse_int(v),
            };
            let suffix = match f.ty {
                FieldType::Int8 => "i8",
                FieldType::Int16 => "i16",
                FieldType::Int32 => "i32",
                FieldType::Int64 => "i64",
                FieldType::Uint16 => "u16",
                _ => "u32",
            };
            format!("{n}{suffix}")
        }
        FieldType::Float64 => match raw {
            None => "0.0".to_string(),
            Some(serde_json::Value::Number(n)) => format!("{}f64", n.as_f64().unwrap()),
            Some(serde_json::Value::String(s)) => format!("{}f64", s),
            other => panic!("bad float default {other:?}"),
        },
        FieldType::Str => match raw {
            None => "String::new()".to_string(),
            Some(serde_json::Value::String(s)) => format!("String::from({s:?})"),
            other => panic!("bad string default {other:?}"),
        },
        // "Uuid fields use a special zero uuid value as a sentinel" — README.
        FieldType::Uuid => "Uuid::ZERO".to_string(),
        FieldType::Bytes => "Bytes::new()".to_string(),
        // "Records fields default to null" — README.
        FieldType::Records => {
            return if optional {
                "None".into()
            } else {
                "Bytes::new()".into()
            }
        }
        FieldType::Struct(n) => format!("{n}::default()"),
        // Turbofished: the default appears in `==` comparisons for tagged-field
        FieldType::Array(inner) => format!("Vec::<{}>::new()", inner.rust_type()),
    };

    if optional {
        format!("Some({inner})")
    } else {
        inner
    }
}

fn parse_int(v: &serde_json::Value) -> i64 {
    match v {
        serde_json::Value::Number(n) => n.as_i64().unwrap_or_else(|| panic!("bad int {n}")),
        serde_json::Value::String(s) => {
            let s = s.trim();
            if let Some(hex) = s.strip_prefix("0x").or_else(|| s.strip_prefix("0X")) {
                i64::from_str_radix(hex, 16).unwrap_or_else(|_| panic!("bad hex default {s:?}"))
            } else {
                s.parse::<i64>()
                    .unwrap_or_else(|_| panic!("bad int default {s:?}"))
            }
        }
        other => panic!("bad int default {other:?}"),
    }
}

fn wrap(s: &str, width: usize) -> Vec<String> {
    let mut lines = Vec::new();
    let mut cur = String::new();
    for word in s.split_whitespace() {
        if !cur.is_empty() && cur.len() + 1 + word.len() > width {
            lines.push(std::mem::take(&mut cur));
        }
        if !cur.is_empty() {
            cur.push(' ');
        }
        cur.push_str(word);
    }
    if !cur.is_empty() {
        lines.push(cur);
    }
    lines
}
